name: Make IPTV EPG 
on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Download WebGrab+Plus
      run: |
        wget http://webgrabplus.com/sites/default/files/download/SW/V3.2.0/WebGrabPlus_V3.2_install.tar.gz
    - name: Extract WebGrabPlus_V3.2_install.tar.gz
      run: |
        tar -zxvf WebGrabPlus_V3.2_install.tar.gz
    - name: Install WebGrab+Plus
      run: |
        cd .wg++
        ./install.sh
    - name: Run
      run: |
        cd .wg++
        ./run.sh
    - name: Download Other EPG
      run: |
        cd .wg++
        wget http://epg.51zmt.top:8000/e.xml
        wget https://raw.githubusercontent.com/Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List/master/epg.xml
    - name: Install xmltv
      run: |
        sudo apt update
        sudo apt -y install xmltv
    - name: Merge EPG
      run: |
        cd .wg++
        tv_cat e.xml epg.xml > merge.xml
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: guide.xml
        path: .wg++/guide.xml
    - name: Git push assets to "main" branch
      run: |
        cd .wg++
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git checkout -b EPG
        git add .
        git commit -m "Update EPG"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin EPG
